// src/lib/components/header.svelte
<script lang="ts">
	import { getAuthenticatedUser } from '$lib/context/user-context';
	import ButtonLink from './button-link.svelte';

	let user = getAuthenticatedUser();
</script>

<header class="item-center flex justify-between border-b-3 border-gray-300 px-4 py-4 md:px-10">
	<menu class="flex items-center gap-2">
		<li>
			<a class="text-2xl font-bold hover:underline" href="/">💰 Spleis</a>
		</li>
	</menu>

	<menu class="flex items-center gap-4">
		<li>
			<ButtonLink href="/spleis/create">Create Spleis</ButtonLink>
		</li>
		<li>
			<ButtonLink variant="ghost" href="/account">{$user.name}</ButtonLink>
		</li>
	</menu>
</header>

// app/components/layout/header.tsx
import { UserButton } from "@clerk/remix";

export const Header = () => {
  return (
    <div className="mb-8 px-4">
      <header className="max-w-screen-xl mx-auto py-4 flex items-center justify-between">
        <div>
          <a href="/hjem">
            <h1 className="font-medium text-xl">{"Spleiser'n"}</h1>
          </a>
        </div>

        <div>
          <nav>
            <ul className="flex items-center gap-2">
              <li>
                <UserButton />
              </li>
            </ul>
          </nav>
        </div>
      </header>
    </div>
  );
};
