// web/src/lib/components/checkbox.svelte
<script lang="ts">
	import { cn } from '$lib/cn';
	import type { HTMLInputAttributes } from 'svelte/elements';

	type Props = Omit<HTMLInputAttributes, 'type'>;

	let { checked = $bindable(), class: className, ...props }: Props = $props();
</script>

<input
	type="checkbox"
	bind:checked
	class={cn(
		'size-5 rounded border-2 border-gray-300 bg-white text-emerald-500 ring-offset-2 checked:bg-emerald-500 focus:ring-2 focus:ring-emerald-500 focus:outline-none',
		className
	)}
	{...props}
/>

// app/components/ui/checkbox.tsx
import { InputHTMLAttributes } from "react";
import { cn } from "~/utils/cn";

type CheckboxProps = InputHTMLAttributes<HTMLInputElement> & {
  ref?: React.Ref<HTMLInputElement>;
};

export const Checkbox = ({ className, ...props }: CheckboxProps) => {
  return (
    <input
      type="checkbox"
      className={cn(
        "w-4 h-4 text-primary bg-gray-100 border-gray-300 rounded focus:ring-primary focus:ring-2",
        className
      )}
      {...props}
    />
  );
};
