// web/src/lib/components/input.svelte
<script lang="ts">
	import { cn } from '$lib/cn';
	import type { HTMLInputAttributes } from 'svelte/elements';

	type Props = HTMLInputAttributes;

	let { value = $bindable(), class: className, ...props }: Props = $props();
</script>

<input
	bind:value
	class={cn(
		'h-10 rounded-lg border-3 border-gray-300 ring-offset-2 focus:ring-2 focus:ring-emerald-500 focus:outline-none',
		className
	)}
	{...props}
/>

// app/components/ui/input.tsx
import { InputHTMLAttributes } from "react";
import { cn } from "~/utils/cn";

type InputProps = InputHTMLAttributes<HTMLInputElement> & {
  ref?: React.Ref<HTMLInputElement>;
};

export const Input = ({ className, ...props }: InputProps) => {
  return (
    <input
      className={cn(
        "border border-gray-300 text-sm font-medium shadow-inner h-8 text-gray-700 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-300 focus:border-transparent px-2 w-full",
        className
      )}
      {...props}
    />
  );
};
